#!/bin/bash

# Remove all symbols before running them all 
kill -9 `ps -ef | grep synergista* | grep -v grep | awk '{print $2}'`
kill -9 `ps -ef | grep synergista* | grep -v grep | awk '{print $2}'`

# Set permission for the executable file
cd /home/app/synergista/
chmod u+x synergista_optimization

# Run symbol GBPUSD all years
nohup ./synergista_optimization GBPUSD 1 & 
nohup ./synergista_optimization GBPUSD 3 &
nohup ./synergista_optimization GBPUSD 5 &


# Check all processes
ps ux | grep synergista*


